### ISSUE TITLE
Add a new field `isPinned` to the topics table to indicate if a topic is pinned.

### ISSUE THREAD

**Issue by lhitmi** [CMU-17313Q/nodebb-f24-logic-lords#12]
This issue addresses the pin announcements user story and will be completed in Sprint 1, with high impact and moderate effort. It involves adding the `isPinned` field to the topics table in the database, ensuring it correctly indicates whether a topic is pinned, which allows important announcements to remain visible at the top of forums. User story is issue #16

**Comment by mohamed-elzeni** [comment]
This is cancelled since it's already implemented in NodeBB.
