### ISSUE TITLE
Update the backend to handle the `isPinned` field by allowing setting and updating the field by admins.

### ISSUE THREAD

**Issue by lhitmi** [CMU-17313Q/nodebb-f24-logic-lords#13]
This issue addresses the pin announcements user story and will be completed in Sprint 1, with high impact and moderate effort.It focuses on updating the backend to allow admins to set and modify the isPinned field for any topic, ensuring that changes are saved correctly and reflected in the database for better management of pinned content.  User story is issue #16

**Comment by mohamed-elzeni** [comment]
This is cancelled since it's already implemented in NodeBB.
