### ISSUE TITLE
Add frontend elements to enable sorting by pinned/unpinned and buttons for pinning/unpinning and pin icons on pinned posts.

### ISSUE THREAD

**Issue by lhitmi** [CMU-17313Q/nodebb-f24-logic-lords#14]
This issue addresses the pin announcements user story and is scheduled for completion in Sprint 1, with high impact and moderate effort. It involves adding front-end functionality to display pin/unpin buttons, show pin icons on pinned posts, and enable sorting by pinned/unpinned status, ensuring all features work seamlessly for users and admins. User story is issue #16

**Comment by mohamed-elzeni** [comment]
This is cancelled since it's already implemented in NodeBB.
