### ISSUE TITLE
Implement basic logic within the function to flag or hide content matching the filter rules.

### ISSUE THREAD

**Issue by lhitmi** [CMU-17313Q/nodebb-f24-logic-lords#5]
This issue addresses the implementation of automated filters as part of the content filtering system. It has high impact due to its essential role in enabling content moderation and requires moderate effort to complete in Sprint 2. The function correctly flags or hides inappropriate content according to the rules. The logic ensures that flagged content is either blocked from publication or sent for admin review, with proper feedback given to users. User story is issue #18

**Comment by mohamed-elzeni** [comment]
This isn't necessary anymore since the filtering happens when creating a post. There is no need to flag posts later on since they are not allowed to be posted in the first place if inappropriate.
