### ISSUE TITLE
Implement a notification system that notifies admins when a bug is reported. 

### ISSUE THREAD

**Issue by lhitmi** [CMU-17313Q/nodebb-f24-logic-lords#7]
This issue addresses the bug reporting user story, which has a high impact for developers and moderate difficulty to complete in Sprint 2. It involves developing a notification system that alerts admins immediately when a bug is reported through the interface, ensuring prompt awareness of issues. Admins should receive instant notifications via the designated channel whenever a bug report is submitted. User story is issue #17

**Comment by mohamed-elzeni** [comment]
This will be cancelled since it makes the user story very complex for only 2 sprints.
